% script de traitement manuel des coupes CTD pour PIRATA-FR31

debut = 5; fin = 28;

%TEMP:

plot_section('LATX','TEMP','profils',[debut:fin],'methode','contourf',...
 'Interpol',10,'Vertical',[0 250;250 2000],'Contour',[0:1:30],'Pas',5,...
  'label','on','ClabelSpec','auto','ProfilSpec','on',...
  'Print',{'png','PIRATA-FR31-CTD-radiale-TEMP-1-30N_10W_20S'} )

%PSAL:
plot_section('LATX','PSAL','profils',[debut:fin],'methode','contourf',...
  'Interpol',10,'Vertical',[0 250;250 2000],'Contour',[31:.1:37],'Pas',.5,...
 'label','on','ClabelSpec','auto','ProfilSpec','on',...
 'Print',{'png','PIRATA-FR31-CTD-radiale-PSAL-1-30N_10W_20S'} )

%DOX2:
plot_section('LATX','DOX2','profils',[debut:fin],'methode','contourf',...
  'Interpol',10,'Vertical',[0 250;250 2000],'Contour',[20:10:220],'Pas',50,...
  'label','on','ClabelSpec','auto','ProfilSpec','on',...
  'Print',{'png','PIRATA-FR31-CTD-radiale-DOX2-1-30N_10W_20S'} )

%FLU2:
plot_section('LATX','FLU2','profils',[debut:fin],'methode','contourf',...
 'Interpol',10,'Vertical',[0 250],'Contour',[0:.2:2],'Pas',1,...
  'label','on','ClabelSpec','auto','ProfilSpec','on',...
  'Print',{'png','PIRATA-FR31-CTD-radiale-FLU2_1-30N_10W_20S'} )


%DENS:
plot_section('LATX','DENS','profils',[debut:fin],'methode','contourf',...
  'Interpol',10,'Vertical',[0 250;250 2000],'Contour',[20:.5:30],'Pas',1,...
  'label','on','ClabelSpec','auto','ProfilSpec','on',...
  'Print',{'png','PIRATA-FR31-CTD-radiale-DENS-1-30N_10W_20S'} )

%% Point fixe n°1: 10W-0

debut = 33; fin = 49;

%TEMP:
plot_section('DAYD','TEMP','profils',[debut:fin],'methode','contourf',...
 'Interpol',10,'Vertical',[0 200],'Contour',[10:1:30],'Pas',5,...
  'label','on','ClabelSpec','auto','ProfilSpec','on',...
  'Print',{'png','PIRATA-FR31-CTD-POINT-FIXE-TEMP-0_10W'} )

%PSAL:
plot_section('DAYD','PSAL','profils',[debut:fin],'methode','contourf',...
  'Interpol',10,'Vertical',[0 200],'Contour',[33:.1:37],'Pas',.5,...
 'label','on','ClabelSpec','auto','ProfilSpec','on',...
 'Print',{'png','PIRATA-FR31-CTD-POINT-FIXE-PSAL-0_10W'} )

%DOX2:
plot_section('DAYD','DOX2','profils',[debut:fin],'methode','contourf',...
  'Interpol',10,'Vertical',[0 200],'Contour',[20:10:220],'Pas',50,...
  'label','on','ClabelSpec','auto','ProfilSpec','on',...
  'Print',{'png','PIRATA-FR31-CTD-POINT-FIXE-DOX2-0_10W'} )

%DENS:
plot_section('DAYD','DENS','profils',[debut:fin],'methode','contourf',...
  'Interpol',10,'Vertical',[0 200],'Contour',[20:.5:30],'Pas',1,...
  'label','on','ClabelSpec','auto','ProfilSpec','on',...
  'Print',{'png','PIRATA-FR31-CTD-POINT-FIXE-DENS-0_10W'} )

%FLU2:
plot_section('DAYD','FLU2','profils',[debut:fin],'methode','contourf',...
  'Interpol',10,'Vertical',[0 200],'Contour',[0:0.2:2],'Pas',1,...
  'label','on','ClabelSpec','auto','ProfilSpec','on',...
  'Print',{'png','PIRATA-FR31-CTD-POINT-FIXE-FLU2-0_10W'} )
% 
