% script de traitement manuel des coupes XBT PIRATA-FR31


% Section Canaries - 0-10W 
% TEMP:
debut = 2; fin = 17; 

plot_section('LATX','TEMP','profils',[debut:fin],...
  'methode','contourf','Interpol',10,'Vertical',[0 250;250 900],...
  'Contour',[0:1:30],'Pas',5,'label','on','ClabelSpec','auto',...
  'ProfilSpec','on',...
  'Print',{'png','PIRATA-FR31-XBT-CANARIES_1-30N-10W'} )


% Section sud 0-10W - 10S-20S
% TEMP:
debut = 18; fin = 28; 

plot_section('LATX','TEMP','profils',[debut:fin],...
  'methode','contourf','Interpol',10,'Vertical',[0 250;250 900],...
  'Contour',[0:1:30],'Pas',5,'label','on','ClabelSpec','auto',...
  'ProfilSpec','on',...
  'Print',{'png','PIRATA-FR31-XBT-TEMP_10W_10S-20S'} )

% Section  10S-10W - 0/0
% TEMP:
debut = 29; fin = 39; 

plot_section('LATX','TEMP','profils',[debut:fin],...
  'methode','contourf','Interpol',10,'Vertical',[0 250;250 900],...
  'Contour',[0:1:30],'Pas',5,'label','on','ClabelSpec','auto',...
  'ProfilSpec','on',...
  'Print',{'png','PIRATA-FR31-XBT-TEMP_10W_10S-0_0'} )


% Section Equatorial
% TEMP:
debut = 39; fin = 53

plot_section('LONX','TEMP','profils',[debut:fin],...
  'methode','contourf','Interpol',10,'Vertical',[0 250;250 900],...
  'Contour',[0:1:30],'Pas',5,'label','on','ClabelSpec','auto',...
  'ProfilSpec','on',...
  'Print',{'png','PIRATA-FR31-XBT-TEMP_10W-23W-0'} )
% 
% 
% % Section 6S - 0-9E 
% % TEMP:
% debut = 32; fin = 38; 
% 
% plot_section('LONX','TEMP','profils',[debut:fin],...
%   'methode','contourf','Interpol',10,'Vertical',[0 250;250 900],...
%   'Contour',[0:1:30],'Pas',5,'label','on','ClabelSpec','auto',...
%   'ProfilSpec','off',...
%   'Print',{'png','PIRATA-FR31-XBT-TEMP_6S-0_9E'} )
% 
% % Section 6S-8E - 10S-10W 
% % TEMP:
% debut = 38; fin = 57; 
% 
% plot_section('LONX','TEMP','profils',[debut:fin],...
%   'methode','contourf','Interpol',10,'Vertical',[0 250;250 900],...
%   'Contour',[0:1:30],'Pas',5,'label','on','ClabelSpec','auto',...
%   'ProfilSpec','off',...
%   'Print',{'png','PIRATA-FR31-XBT-TEMP_6S-8E_10S-10W'} )
% 
% % Section 4N-23W - Midelo 
% % TEMP:
% debut = 72; fin = 84; 
% 
% plot_section('LATX','TEMP','profils',[debut:fin],...
%   'methode','contourf','Interpol',10,'Vertical',[0 250;250 900],...
%   'Contour',[0:1:30],'Pas',5,'label','on','ClabelSpec','auto',...
%   'ProfilSpec','off',...
%   'Print',{'png','PIRATA-FR31-XBT-TEMP_4N-23W_MIDELO'} )
