function plot_menu
% initialize the plot menu for LADCP processing
%
% version 0.4	last change 16.11.2012

% G.Krahmann, IFM-GEOMAR, 2004

% changed location of windows for OSX     GK, 15.07.2008  0.2-->0.3
% use sfigure instead of figure           GK, 16.11.2012  0.3-->0.4

dd = dir('tmp/*.fig');
for n=1:length(dd)
  delete(['tmp/',dd(n).name])
end

global mh

% handle newer matlab versions
if version('-release')>=14
  imac = 0;
else
  imac = ismac;
end

% create 2 windows
% one for the control menu and one for the actual plots

sfigure(1);
clf
set(gcf,'units','normalized','position',[0 0 .15 1],'numbertitle','off','menubar',...
  'none','name','LADCP 1');
sfigure(2);
clf
set(gcf,'units','normalized','position',[.19 0 .8 1],'numbertitle','off',...
  'name','LADCP 2');

% create the menu
sfigure(1);
uicontrol('style','frame','units','normalized','position',[.03 .01 .94 .86],'parent',1);
uicontrol('style','frame','units','normalized','position',[.03 .88 .94 .11],'parent',1);


uicontrol('style','text','units','normalized','position',[0.05,0.96,0.90,0.03],...
  'horizontalalignment','center','string','LADCP',...
  'fontsize',18,'fontweight','bold','parent',1);
uicontrol('style','text','units','normalized','position',[0.05,0.93,0.90,0.03],...
  'horizontalalignment','center','string','processing',...
  'fontsize',18,'fontweight','bold','parent',1);
uicontrol('style','text','units','normalized','position',[0.05,0.89,0.90,0.03],...
  'horizontalalignment','center','string','display',...
  'fontsize',18,'fontweight','bold','parent',1);

mh(1) = uicontrol('style','push','units','normalized','position',[.05 .83 .90 .03],...
  'horizontalalignment','center','string','UV-profiles','parent',1,...
  'callback',{@plot_controls, 1});
mh(2) = uicontrol('style','push','units','normalized','position',[.05 .78 .90 .03],...
  'horizontalalignment','center','string','W,Z,sensors','parent',1,...
  'callback',{@plot_controls, 2});
mh(3) = uicontrol('style','push','units','normalized','position',[.05 .73 .90 .03],...
  'horizontalalignment','center','string','ERR-profiles','parent',1,...
  'callback',{@plot_controls, 3});
mh(4) = uicontrol('style','push','units','normalized','position',[.05 .68 .90 .03],...
  'horizontalalignment','center','string','SURF/BOT recog.','parent',1,...
  'callback',{@plot_controls, 4});
mh(5) = uicontrol('style','push','units','normalized','position',[.05 .63 .90 .03],...
  'horizontalalignment','center','string','Heading dual','parent',1,...
  'callback',{@plot_controls, 5});
mh(6) = uicontrol('style','push','units','normalized','position',[.05 .58 .90 .03],...
  'horizontalalignment','center','string','HDG/PIT/ROL','parent',1,...
  'callback',{@plot_controls, 6});
mh(7) = uicontrol('style','push','units','normalized','position',[.05 .53 .90 .03],...
  'horizontalalignment','center','string','CTD motion','parent',1,...
  'callback',{@plot_controls, 7});
mh(8) = uicontrol('style','push','units','normalized','position',[.05 .48 .90 .03],...
  'horizontalalignment','center','string','CTD-LADCP merging','parent',1,...
  'callback',{@plot_controls, 8});
mh(9) = uicontrol('style','push','units','normalized','position',[.05 .43 .90 .03],...
  'horizontalalignment','center','string','SADCP','parent',1,...
  'callback',{@plot_controls, 9});
mh(10) = uicontrol('style','push','units','normalized','position',[.05 .38 .90 .03],...
  'horizontalalignment','center','string','Vel offset','parent',1,...
  'callback',{@plot_controls, 10});
mh(11) = uicontrol('style','push','units','normalized','position',[.05 .33 .90 .03],...
  'horizontalalignment','center','string','Warnings','parent',1,...
  'callback',{@plot_controls, 11});
mh(12) = uicontrol('style','push','units','normalized','position',[.05 .28 .90 .03],...
  'horizontalalignment','center','string','Inv. Weights','parent',1,...
  'callback',{@plot_controls, 12});
mh(13) = uicontrol('style','push','units','normalized','position',[.05 .23 .90 .03],...
  'horizontalalignment','center','string','Bottom Track','parent',1,...
  'callback',{@plot_controls, 13});
mh(14) = uicontrol('style','push','units','normalized','position',[.05 .18 .90 .03],...
  'horizontalalignment','center','string','TargetStr Edited','parent',1,...
  'callback',{@plot_controls, 14});
mh(15) = uicontrol('style','push','units','normalized','position',[.05 .13 .90 .03],...
  'horizontalalignment','center','string','Correl. Edited','parent',1,...
  'callback',{@plot_controls, 15});
mh(16) = uicontrol('style','push','units','normalized','position',[.05 .08 .90 .03],...
  'horizontalalignment','center','string','INV. Weights 2','parent',1,...
  'callback',{@plot_controls, 16});


% nested function plot_controls
% control function for LADCP plotmenu
  function [] = plot_controls(obj, ~, fig)
    
    % reloads the stored figure into the display window  
    figload(['tmp/',int2str(fig),'.fig'],2) 
    figure(1)
    
    % find selected control and set it black
    set(findobj('foregroundcolor',[1,0,0]),'foregroundcolor',[0,0,0]);
    % set selected control to red
    set(obj,'foregroundcolor',[1,0,0]);

    
  end % end of plot_controls

end % end of plot_menu

